### ISSUE TITLE
mosquitto package fails to install

### ISSUE THREAD

**Issue by garethhowell** [salt-formulas/salt-formula-mosquitto#2]
I'm trying to use this formula, with the metadata as supplied, to install mosquitto on a debian 9 host. I get the following when `salt` is run:
```
          ID: mosquitto_packages
    Function: pkg.installed
        Name: u'mosquitto'
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit run-r063080065cfe444894c46769470db778.scope.
                    E: Unable to locate package u'mosquitto'
     Started: 12:47:55.058945
    Duration: 4640.654 ms
     Changes:   

```
It looks like a unicode problem, but I can't see any references to unicode anywhere.
